### ISSUE TITLE
지도 이동하려고 마우스 드래그시 이미지로 처리됨

### ISSUE THREAD

**Issue by Syangki** [xe-public/map_components#10]
![default](https://cloud.githubusercontent.com/assets/8645135/8511505/3116a342-2355-11e5-97ef-229e1537287e.png)

보시는바와같이 이동할때마다 팝업(?)모달(?)창이 떠서 불편합니다. PC에서만 그러네요

xe 1.7.12 윈도우8.1 크롬,파폭 테스트해봄.

**Comment by misol** [comment]
라이트박스 애드온 때문인데.. 회피할 수 있는지 확인하겠습니다.

**Comment by misol** [comment]
https://github.com/xe-public/map_components/commit/0f4f84847911837e5261b8f414360cc57aa62a75 에서 해결해보았고, 1.1.5 버전으로 배포될 예정입니다.
