### ISSUE TITLE
코어가 업데이트 된 영향인지 현위치 표시가 안되네요.

### ISSUE THREAD

**Issue by wookho** [xe-public/map_components#11]
지도로 모임장소 찾을때 유용하게 사용했던 기능인데요.
지금은 지도에 내 위치가 안나오니 목적지까지 찾아가는데 예전보다 어려움이 있습니다.
커뮤니티에서 알려드린 적이 있는데요. 혹시나 남깁니다.

**Comment by misol** [comment]
이슈 남겨주셔서 감사합니다.

**Comment by wookho** [comment]
말씀하신대로 제 기기 자체 위치 기능이 꺼져 있었네요.
