### ISSUE TITLE
모바일에 대한 배려....

### ISSUE THREAD

**Issue by Syangki** [xe-public/map_components#8]
모바일 디바이스가 급속도로 퍼지고있는데
본문에 지도컴포넌트를 삽입하게되면 모바일 디바이스에서 레이아웃이 깨지는(지도 컴포넌트가 밖으로 삐져나옴) 현상이 있습니다.

13년 8월에 출시한(?) [구글 지도 컴포넌트는](https://www.xpressengine.com/index.php?mid=download&package_id=18673912) 모바일에서도 적절하게 대응을 하더군요.

이에따른 모바일 디바이스에 대한 배려가 있으면 좋겠습니다.

**Comment by misol** [comment]
고민해보겠습니다.

**Comment by misol** [comment]
https://github.com/xe-public/map_components/commit/0f4f84847911837e5261b8f414360cc57aa62a75 에서 해결해보았고, 1.1.5 버전으로 배포될 예정입니다.
