### ISSUE TITLE
지도 v1/v2 api 종료..

### ISSUE THREAD

**Issue by Syangki** [xe-public/map_components#9]
http://daumdna.tistory.com/842

글을 보시면 7월1일자로 종료되엇다고 나옵니다. api 발급받는 부분도 컴퍼넌트 설정부분에 설명된것과 지금 완전 달라졌습니다. 확인부탁드려요

**Comment by misol** [comment]
확인해보겠습니다.

**Comment by misol** [comment]
Fixed at https://github.com/xe-public/map_components/commit/db8676f8c4cce4baec7aba4700f7775ca0541d8b

이 내용을 고친 1.1.3 버전을 깃 허브에 배포하였고, XE 공홈에 배포 요청 하였습니다.
XE 공홈에서는 월요일 또는 화요일쯤 확인하실 수 있습니다.
